import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { generateGuideSchema } from '@/lib/utils/validation';
import { successResponse, badRequestResponse, notFoundResponse, internalErrorResponse } from '@/lib/utils/api-response';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    const validation = generateGuideSchema.safeParse(body);
    if (!validation.success) {
      return badRequestResponse('Invalid input');
    }

    const { vocId, authorId } = validation.data;

    // Check if VOC exists
    const voc = await prisma.vOC.findUnique({
      where: { id: vocId },
    });

    if (!voc) {
      return notFoundResponse('VOC not found');
    }

    // Check if author exists
    const author = await prisma.user.findUnique({
      where: { id: authorId },
    });

    if (!author) {
      return badRequestResponse('Author not found');
    }

    // Generate a job ID for tracking
    const jobId = `guide-gen-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

    // TODO: In production, this should call the RAG service asynchronously
    // For now, we'll create a placeholder response
    //
    // Example RAG service call:
    // const ragServiceUrl = process.env.RAG_SERVICE_URL;
    // fetch(`${ragServiceUrl}/generate`, {
    //   method: 'POST',
    //   headers: { 'Content-Type': 'application/json' },
    //   body: JSON.stringify({
    //     vocId,
    //     jiraKey: voc.jiraKey,
    //     title: voc.title,
    //     description: voc.description,
    //     category: voc.category,
    //   }),
    // });

    // Background process simulation (in production, use a job queue)
    // This is a placeholder for demonstration
    setTimeout(async () => {
      try {
        // Simulate RAG service response
        const generatedContent = {
          title: `Solution Guide for ${voc.jiraKey}`,
          problem: `Issue: ${voc.title}\n\nDescription: ${voc.description}`,
          cause: 'Analysis pending - generated by AI',
          procedure: '1. Identify the root cause\n2. Apply solution\n3. Verify resolution',
          solution: 'Detailed solution will be generated by RAG service',
          sources: JSON.stringify([
            { title: 'SCP Documentation', url: 'https://docs.example.com' },
            { title: 'Related Confluence Page', url: 'https://confluence.example.com' },
          ]),
        };

        await prisma.guide.create({
          data: {
            vocId,
            authorId,
            ...generatedContent,
            status: 'DRAFT',
          },
        });

        console.log(`Guide generated for VOC ${vocId} with job ID ${jobId}`);
      } catch (error) {
        console.error(`Error in background guide generation for job ${jobId}:`, error);
      }
    }, 100);

    return successResponse(
      {
        message: 'Guide generation started',
        jobId,
      },
      202
    );
  } catch (error) {
    console.error('Error starting guide generation:', error);
    return internalErrorResponse();
  }
}
