import type { VOC, Guide, DashboardStats } from './types'

export const mockVOCs: VOC[] = [
  {
    id: '1',
    jiraKey: 'VOC-101',
    title: 'Login page showing 500 error on Safari',
    description: 'Users report that the login page fails with a 500 error when accessing from Safari browser. Chrome and Firefox work fine.',
    category: 'Authentication',
    status: 'NEW',
    priority: 'URGENT',
    createdAt: '2026-04-10T10:30:00Z',
    updatedAt: '2026-04-10T10:30:00Z',
  },
  {
    id: '2',
    jiraKey: 'VOC-102',
    title: 'Payment gateway timeout during peak hours',
    description: 'Multiple customers experiencing payment timeouts between 2-4 PM daily. Transaction logs show gateway response delays.',
    category: 'Payment',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    createdAt: '2026-04-09T14:20:00Z',
    updatedAt: '2026-04-11T09:15:00Z',
  },
  {
    id: '3',
    jiraKey: 'VOC-103',
    title: 'Dashboard loading time exceeds 5 seconds',
    description: 'Dashboard takes too long to load for users with large datasets. Performance metrics indicate N+1 query issues.',
    category: 'Performance',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    createdAt: '2026-04-08T16:45:00Z',
    updatedAt: '2026-04-11T11:30:00Z',
  },
  {
    id: '4',
    jiraKey: 'VOC-104',
    title: 'Mobile app crashes on Android 12',
    description: 'Android 12 users report app crashes when uploading images. Stack trace shows memory allocation error.',
    category: 'UI/UX',
    status: 'RESOLVED',
    priority: 'HIGH',
    createdAt: '2026-04-07T09:00:00Z',
    updatedAt: '2026-04-10T17:20:00Z',
  },
  {
    id: '5',
    jiraKey: 'VOC-105',
    title: 'API rate limiting too aggressive',
    description: 'Users hitting rate limits during normal usage. Current limit is 100 req/min which seems too low.',
    category: 'API',
    status: 'NEW',
    priority: 'MEDIUM',
    createdAt: '2026-04-11T08:15:00Z',
    updatedAt: '2026-04-11T08:15:00Z',
  },
]

export const mockGuides: Guide[] = [
  {
    id: 'g1',
    vocId: '3',
    title: 'Dashboard Performance Optimization Guide',
    problem: 'Dashboard loading time exceeds 5 seconds for users with large datasets',
    cause: 'N+1 query pattern detected in user data fetching. Each dashboard widget makes separate database queries instead of batch loading.',
    procedure: '1. Identify slow queries using database profiler\n2. Implement query batching for dashboard widgets\n3. Add database indices on frequently joined tables\n4. Implement Redis caching for static dashboard data\n5. Test with production-scale dataset',
    solution: 'Refactor dashboard data loader to use batch queries and add Redis cache layer. Expected improvement: 5s → 0.8s load time.',
    sources: 'Database logs, APM traces, similar issue: VOC-089',
    status: 'PENDING_APPROVAL',
    createdAt: '2026-04-11T11:30:00Z',
    updatedAt: '2026-04-11T11:30:00Z',
  },
  {
    id: 'g2',
    vocId: '2',
    title: 'Payment Gateway Timeout Resolution',
    problem: 'Payment gateway experiencing timeouts during peak hours (2-4 PM)',
    cause: 'Payment service connection pool size limited to 10. Peak traffic requires 50+ concurrent connections.',
    procedure: '1. Increase connection pool size to 100\n2. Implement connection retry logic with exponential backoff\n3. Add circuit breaker pattern for gateway failures\n4. Set up queue for payment processing during high load\n5. Monitor connection pool metrics',
    solution: 'Increase connection pool, add retry logic, and implement async payment queue for resilience.',
    sources: 'Payment service logs, infrastructure metrics, vendor documentation',
    status: 'APPROVED',
    createdAt: '2026-04-11T09:15:00Z',
    updatedAt: '2026-04-11T15:20:00Z',
    approvedBy: 'admin@example.com',
    approvedAt: '2026-04-11T15:20:00Z',
  },
  {
    id: 'g3',
    vocId: '4',
    title: 'Android 12 Image Upload Fix',
    problem: 'Mobile app crashes on Android 12 when uploading images',
    cause: 'Android 12 introduced stricter memory allocation limits. Current image processing loads entire file into memory before compression.',
    procedure: '1. Implement streaming image compression\n2. Add memory limit checks before processing\n3. Use Android 12 compatible image handling APIs\n4. Test on multiple Android 12 devices\n5. Add error handling for OOM scenarios',
    solution: 'Refactor image upload to use streaming compression and Android 12 APIs.',
    sources: 'Android crash logs, Android 12 migration guide, Stack Overflow #12345',
    status: 'APPROVED',
    createdAt: '2026-04-10T14:00:00Z',
    updatedAt: '2026-04-10T17:20:00Z',
    approvedBy: 'tech.lead@example.com',
    approvedAt: '2026-04-10T17:20:00Z',
  },
]

export const mockDashboardStats: DashboardStats = {
  totalVOCs: 5,
  pendingGuides: 1,
  approvedGuides: 2,
  resolvedVOCs: 1,
}
